package co.edu.icesi.dev.outcome_curr_mgmt.service.perm_types.curriculum_qa;

import co.edu.icesi.dev.outcome_curr_mgmt.model.enums.AssessmentGenPlanStatus;
import co.edu.icesi.dev.outcome_curr_mgmt.model.enums.BaseStatus;
import co.edu.icesi.dev.outcome_curr_mgmt.service.perm_types.BasePermLevel;
import co.edu.icesi.dev.outcome_curr_mgmt.service.validator.faculty.UserPermAccess;

import java.util.List;
import java.util.Map;

import static co.edu.icesi.dev.outcome_curr.mgmt.rs.curriculum_qa.AuthAssessmentGlenPlanPermissions.*;

public interface AssessmentGenPlanPermType {
    //TODO add test coverage
    //Permission for AcadProgramService related to Faculty - When faculty only global are relevant for other faculties
    Map<UserPermAccess, List<String>> ASSEMTGENPLAN_FUTURE_FACULTIES = Map.of(UserPermAccess.ADMIN,
            List.of(ROLE_ADMIN_FUTURE_GEN_ASSMNT_PLAN_ANY), UserPermAccess.QUERY,
            List.of(ROLE_ADMIN_FUTURE_GEN_ASSMNT_PLAN_ANY, ROLE_QUERY_FUTURE_GEN_ASSMNT_PLAN_ANY),
            UserPermAccess.UPDATE,
            List.of(ROLE_UPDATE_STATUS_FUTURE_GEN_ASSMNT_PLAN_ANY));
    Map<UserPermAccess, List<String>> ASSEMTGENPLAN_FUTURE_FACULTY = Map.of(UserPermAccess.ADMIN,
            List.of(ROLE_ADMIN_FUTURE_GEN_ASSMNT_PLAN_FAC, ROLE_ADMIN_FUTURE_GEN_ASSMNT_PLAN_PRG,
                    ROLE_ADMIN_FUTURE_GEN_ASSMNT_PLAN_OWN), UserPermAccess.QUERY,
            List.of(ROLE_ADMIN_FUTURE_GEN_ASSMNT_PLAN_FAC, ROLE_ADMIN_FUTURE_GEN_ASSMNT_PLAN_PRG,
                    ROLE_ADMIN_FUTURE_GEN_ASSMNT_PLAN_OWN, ROLE_QUERY_FUTURE_GEN_ASSMNT_PLAN_FAC,
                    ROLE_QUERY_FUTURE_GEN_ASSMNT_PLAN_PRG, ROLE_QUERY_FUTURE_GEN_ASSMNT_PLAN_OWN),
            UserPermAccess.UPDATE,
            List.of(ROLE_UPDATE_STATUS_FUTURE_GEN_ASSMNT_PLAN_FAC, ROLE_UPDATE_STATUS_FUTURE_GEN_ASSMNT_PLAN_PRG));
    Map<UserPermAccess, List<String>> ASSEMTGENPLAN_EXECUTING_FACULTIES = Map.of(UserPermAccess.ADMIN,
            List.of(ROLE_ADMIN_EXEC_GEN_ASSMNT_PLAN_ANY), UserPermAccess.QUERY,
            List.of(ROLE_ADMIN_EXEC_GEN_ASSMNT_PLAN_ANY, ROLE_QUERY_EXEC_GEN_ASSMNT_PLAN_ANY), UserPermAccess.UPDATE,
            List.of(ROLE_UPDATE_STATUS_EXEC_GEN_ASSMNT_PLAN_ANY));
    Map<UserPermAccess, List<String>> ASSEMTGENPLAN_EXECUTING_FACULTY = Map.of(UserPermAccess.ADMIN,
            List.of(ROLE_ADMIN_EXEC_GEN_ASSMNT_PLAN_FAC, ROLE_ADMIN_EXEC_GEN_ASSMNT_PLAN_PRG,
                    ROLE_ADMIN_EXEC_GEN_ASSMNT_PLAN_OWN), UserPermAccess.QUERY,
            List.of(ROLE_ADMIN_EXEC_GEN_ASSMNT_PLAN_FAC, ROLE_ADMIN_EXEC_GEN_ASSMNT_PLAN_PRG,
                    ROLE_ADMIN_EXEC_GEN_ASSMNT_PLAN_OWN, ROLE_QUERY_EXEC_GEN_ASSMNT_PLAN_FAC,
                    ROLE_QUERY_EXEC_GEN_ASSMNT_PLAN_PRG, ROLE_QUERY_EXEC_GEN_ASSMNT_PLAN_OWN), UserPermAccess.UPDATE,
            List.of(ROLE_UPDATE_STATUS_EXEC_GEN_ASSMNT_PLAN_FAC, ROLE_UPDATE_STATUS_EXEC_GEN_ASSMNT_PLAN_PRG));
    Map<UserPermAccess, List<String>> ASSEMTGENPLAN_REVIEW_FACULTIES = Map.of(UserPermAccess.ADMIN,
            List.of(ROLE_ADMIN_REVIEW_GEN_ASSMNT_PLAN_ANY), UserPermAccess.QUERY,
            List.of(ROLE_ADMIN_REVIEW_GEN_ASSMNT_PLAN_ANY, ROLE_QUERY_REVIEW_GEN_ASSMNT_PLAN_ANY),
            UserPermAccess.UPDATE,
            List.of(ROLE_UPDATE_STATUS_REVIEW_GEN_ASSMNT_PLAN_ANY));
    Map<UserPermAccess, List<String>> ASSEMTGENPLAN_REVIEW_FACULTY = Map.of(UserPermAccess.ADMIN,
            List.of(ROLE_ADMIN_REVIEW_GEN_ASSMNT_PLAN_FAC, ROLE_ADMIN_REVIEW_GEN_ASSMNT_PLAN_PRG,
                    ROLE_ADMIN_REVIEW_GEN_ASSMNT_PLAN_OWN), UserPermAccess.QUERY,
            List.of(ROLE_ADMIN_REVIEW_GEN_ASSMNT_PLAN_FAC, ROLE_ADMIN_REVIEW_GEN_ASSMNT_PLAN_PRG,
                    ROLE_ADMIN_REVIEW_GEN_ASSMNT_PLAN_OWN, ROLE_QUERY_REVIEW_GEN_ASSMNT_PLAN_FAC,
                    ROLE_QUERY_REVIEW_GEN_ASSMNT_PLAN_PRG, ROLE_QUERY_REVIEW_GEN_ASSMNT_PLAN_OWN),
            UserPermAccess.UPDATE,
            List.of(ROLE_UPDATE_STATUS_REVIEW_GEN_ASSMNT_PLAN_FAC, ROLE_UPDATE_STATUS_REVIEW_GEN_ASSMNT_PLAN_PRG));
    Map<UserPermAccess, List<String>> ASSEMTGENPLAN_CLOSED_FACULTIES = Map.of(UserPermAccess.ADMIN,
            List.of(ROLE_ADMIN_CLOSED_GEN_ASSMNT_PLAN_ANY), UserPermAccess.QUERY,
            List.of(ROLE_ADMIN_CLOSED_GEN_ASSMNT_PLAN_ANY, ROLE_QUERY_CLOSED_GEN_ASSMNT_PLAN_ANY),
            UserPermAccess.UPDATE,
            List.of(ROLE_UPDATE_STATUS_CLOSED_GEN_ASSMNT_PLAN_ANY));
    Map<UserPermAccess, List<String>> ASSEMTGENPLAN_CLOSED_FACULTY = Map.of(UserPermAccess.ADMIN,
            List.of(ROLE_ADMIN_CLOSED_GEN_ASSMNT_PLAN_FAC, ROLE_ADMIN_CLOSED_GEN_ASSMNT_PLAN_PRG,
                    ROLE_ADMIN_CLOSED_GEN_ASSMNT_PLAN_OWN), UserPermAccess.QUERY,
            List.of(ROLE_ADMIN_CLOSED_GEN_ASSMNT_PLAN_FAC, ROLE_ADMIN_CLOSED_GEN_ASSMNT_PLAN_PRG,
                    ROLE_ADMIN_CLOSED_GEN_ASSMNT_PLAN_OWN, ROLE_QUERY_CLOSED_GEN_ASSMNT_PLAN_FAC,
                    ROLE_QUERY_CLOSED_GEN_ASSMNT_PLAN_PRG, ROLE_QUERY_CLOSED_GEN_ASSMNT_PLAN_OWN),
            UserPermAccess.UPDATE,
            List.of(ROLE_UPDATE_STATUS_CLOSED_GEN_ASSMNT_PLAN_FAC, ROLE_UPDATE_STATUS_CLOSED_GEN_ASSMNT_PLAN_PRG));

    //Permission for AcadProgramService related to AcadProgram - When program, global and faculty are relevant for other programs
    Map<UserPermAccess, List<String>> ASSEMTGENPLAN_FUTURE_ACADPROGRAMS = Map.of(UserPermAccess.ADMIN,
            List.of(ROLE_ADMIN_FUTURE_GEN_ASSMNT_PLAN_ANY, ROLE_ADMIN_FUTURE_GEN_ASSMNT_PLAN_FAC), UserPermAccess.QUERY,
            List.of(ROLE_ADMIN_FUTURE_GEN_ASSMNT_PLAN_ANY, ROLE_ADMIN_FUTURE_GEN_ASSMNT_PLAN_FAC,
                    ROLE_QUERY_FUTURE_GEN_ASSMNT_PLAN_ANY, ROLE_QUERY_FUTURE_GEN_ASSMNT_PLAN_FAC),
            UserPermAccess.UPDATE,
            List.of(ROLE_UPDATE_STATUS_FUTURE_GEN_ASSMNT_PLAN_ANY, ROLE_UPDATE_STATUS_FUTURE_GEN_ASSMNT_PLAN_FAC));
    Map<UserPermAccess, List<String>> ASSEMTGENPLAN_FUTURE_ACADPROGRAM = Map.of(UserPermAccess.ADMIN,
            List.of(ROLE_ADMIN_FUTURE_GEN_ASSMNT_PLAN_PRG, ROLE_ADMIN_FUTURE_GEN_ASSMNT_PLAN_OWN), UserPermAccess.QUERY,
            List.of(ROLE_ADMIN_FUTURE_GEN_ASSMNT_PLAN_PRG, ROLE_ADMIN_FUTURE_GEN_ASSMNT_PLAN_OWN,
                    ROLE_QUERY_FUTURE_GEN_ASSMNT_PLAN_PRG, ROLE_QUERY_FUTURE_GEN_ASSMNT_PLAN_OWN),
            UserPermAccess.UPDATE, List.of(ROLE_UPDATE_STATUS_FUTURE_GEN_ASSMNT_PLAN_PRG));
    Map<UserPermAccess, List<String>> ASSEMTGENPLAN_EXECUTING_ACADPROGRAMS = Map.of(UserPermAccess.ADMIN,
            List.of(ROLE_ADMIN_EXEC_GEN_ASSMNT_PLAN_ANY, ROLE_ADMIN_EXEC_GEN_ASSMNT_PLAN_FAC), UserPermAccess.QUERY,
            List.of(ROLE_ADMIN_EXEC_GEN_ASSMNT_PLAN_ANY, ROLE_ADMIN_EXEC_GEN_ASSMNT_PLAN_FAC,
                    ROLE_QUERY_EXEC_GEN_ASSMNT_PLAN_ANY, ROLE_QUERY_EXEC_GEN_ASSMNT_PLAN_FAC), UserPermAccess.UPDATE,
            List.of(ROLE_UPDATE_STATUS_EXEC_GEN_ASSMNT_PLAN_ANY, ROLE_UPDATE_STATUS_EXEC_GEN_ASSMNT_PLAN_FAC));
    Map<UserPermAccess, List<String>> ASSEMTGENPLAN_EXECUTING_ACADPROGRAM = Map.of(UserPermAccess.ADMIN,
            List.of(ROLE_ADMIN_EXEC_GEN_ASSMNT_PLAN_PRG, ROLE_ADMIN_EXEC_GEN_ASSMNT_PLAN_OWN), UserPermAccess.QUERY,
            List.of(ROLE_ADMIN_EXEC_GEN_ASSMNT_PLAN_PRG, ROLE_ADMIN_EXEC_GEN_ASSMNT_PLAN_OWN,
                    ROLE_QUERY_EXEC_GEN_ASSMNT_PLAN_PRG, ROLE_QUERY_EXEC_GEN_ASSMNT_PLAN_OWN), UserPermAccess.UPDATE,
            List.of(ROLE_UPDATE_STATUS_EXEC_GEN_ASSMNT_PLAN_PRG));
    Map<UserPermAccess, List<String>> ASSEMTGENPLAN_REVIEW_ACADPROGRAMS = Map.of(UserPermAccess.ADMIN,
            List.of(ROLE_ADMIN_REVIEW_GEN_ASSMNT_PLAN_ANY, ROLE_ADMIN_REVIEW_GEN_ASSMNT_PLAN_FAC), UserPermAccess.QUERY,
            List.of(ROLE_ADMIN_REVIEW_GEN_ASSMNT_PLAN_ANY, ROLE_ADMIN_REVIEW_GEN_ASSMNT_PLAN_FAC,
                    ROLE_QUERY_REVIEW_GEN_ASSMNT_PLAN_ANY, ROLE_QUERY_REVIEW_GEN_ASSMNT_PLAN_FAC),
            UserPermAccess.UPDATE,
            List.of(ROLE_UPDATE_STATUS_REVIEW_GEN_ASSMNT_PLAN_ANY, ROLE_UPDATE_STATUS_REVIEW_GEN_ASSMNT_PLAN_FAC));
    Map<UserPermAccess, List<String>> ASSEMTGENPLAN_REVIEW_ACADPROGRAM = Map.of(UserPermAccess.ADMIN,
            List.of(ROLE_ADMIN_REVIEW_GEN_ASSMNT_PLAN_PRG, ROLE_ADMIN_REVIEW_GEN_ASSMNT_PLAN_OWN), UserPermAccess.QUERY,
            List.of(ROLE_ADMIN_REVIEW_GEN_ASSMNT_PLAN_PRG, ROLE_ADMIN_REVIEW_GEN_ASSMNT_PLAN_OWN,
                    ROLE_QUERY_REVIEW_GEN_ASSMNT_PLAN_PRG, ROLE_QUERY_REVIEW_GEN_ASSMNT_PLAN_OWN),
            UserPermAccess.UPDATE, List.of(ROLE_UPDATE_STATUS_REVIEW_GEN_ASSMNT_PLAN_PRG));
    Map<UserPermAccess, List<String>> ASSEMTGENPLAN_CLOSED_ACADPROGRAMS = Map.of(UserPermAccess.ADMIN,
            List.of(ROLE_ADMIN_CLOSED_GEN_ASSMNT_PLAN_ANY, ROLE_ADMIN_CLOSED_GEN_ASSMNT_PLAN_FAC), UserPermAccess.QUERY,
            List.of(ROLE_ADMIN_CLOSED_GEN_ASSMNT_PLAN_ANY, ROLE_ADMIN_CLOSED_GEN_ASSMNT_PLAN_FAC,
                    ROLE_QUERY_CLOSED_GEN_ASSMNT_PLAN_ANY, ROLE_QUERY_CLOSED_GEN_ASSMNT_PLAN_FAC),
            UserPermAccess.UPDATE,
            List.of(ROLE_UPDATE_STATUS_CLOSED_GEN_ASSMNT_PLAN_ANY, ROLE_UPDATE_STATUS_CLOSED_GEN_ASSMNT_PLAN_FAC));
    Map<UserPermAccess, List<String>> ASSEMTGENPLAN_CLOSED_ACADPROGRAM = Map.of(UserPermAccess.ADMIN,
            List.of(ROLE_ADMIN_CLOSED_GEN_ASSMNT_PLAN_PRG, ROLE_ADMIN_CLOSED_GEN_ASSMNT_PLAN_OWN), UserPermAccess.QUERY,
            List.of(ROLE_ADMIN_CLOSED_GEN_ASSMNT_PLAN_PRG, ROLE_ADMIN_CLOSED_GEN_ASSMNT_PLAN_OWN,
                    ROLE_QUERY_CLOSED_GEN_ASSMNT_PLAN_PRG, ROLE_QUERY_CLOSED_GEN_ASSMNT_PLAN_OWN),
            UserPermAccess.UPDATE, List.of(ROLE_UPDATE_STATUS_CLOSED_GEN_ASSMNT_PLAN_PRG));

    //Permission for AssesmentGenPlanService related to AssemtGenPlan  - When assess, global faculty and program are relevant for other assessments
    Map<UserPermAccess, List<String>> ASSEMTGENPLAN_FUTURE_ASSEMTGENPLANS = Map.of(UserPermAccess.ADMIN,
            List.of(ROLE_ADMIN_FUTURE_GEN_ASSMNT_PLAN_ANY, ROLE_ADMIN_FUTURE_GEN_ASSMNT_PLAN_FAC,
                    ROLE_ADMIN_FUTURE_GEN_ASSMNT_PLAN_PRG), UserPermAccess.QUERY,
            List.of(ROLE_ADMIN_FUTURE_GEN_ASSMNT_PLAN_ANY, ROLE_ADMIN_FUTURE_GEN_ASSMNT_PLAN_FAC,
                    ROLE_ADMIN_FUTURE_GEN_ASSMNT_PLAN_PRG, ROLE_QUERY_FUTURE_GEN_ASSMNT_PLAN_ANY,
                    ROLE_QUERY_FUTURE_GEN_ASSMNT_PLAN_FAC, ROLE_QUERY_FUTURE_GEN_ASSMNT_PLAN_PRG),
            UserPermAccess.UPDATE,
            List.of(ROLE_UPDATE_STATUS_FUTURE_GEN_ASSMNT_PLAN_ANY, ROLE_UPDATE_STATUS_FUTURE_GEN_ASSMNT_PLAN_FAC,
                    ROLE_UPDATE_STATUS_FUTURE_GEN_ASSMNT_PLAN_PRG));
    Map<UserPermAccess, List<String>> ASSEMTGENPLAN_FUTURE_ASSEMTGENPLAN = Map.of(UserPermAccess.ADMIN,
            List.of(ROLE_ADMIN_FUTURE_GEN_ASSMNT_PLAN_OWN), UserPermAccess.QUERY,
            List.of(ROLE_ADMIN_FUTURE_GEN_ASSMNT_PLAN_OWN, ROLE_QUERY_FUTURE_GEN_ASSMNT_PLAN_OWN),
            UserPermAccess.UPDATE, List.of());

    Map<UserPermAccess, List<String>> ASSEMTGENPLAN_EXECUTING_ASSEMTGENPLANS = Map.of(UserPermAccess.ADMIN,
            List.of(ROLE_ADMIN_EXEC_GEN_ASSMNT_PLAN_ANY, ROLE_ADMIN_EXEC_GEN_ASSMNT_PLAN_FAC,
                    ROLE_ADMIN_EXEC_GEN_ASSMNT_PLAN_PRG), UserPermAccess.QUERY,
            List.of(ROLE_ADMIN_EXEC_GEN_ASSMNT_PLAN_ANY, ROLE_ADMIN_EXEC_GEN_ASSMNT_PLAN_FAC,
                    ROLE_ADMIN_EXEC_GEN_ASSMNT_PLAN_PRG, ROLE_QUERY_EXEC_GEN_ASSMNT_PLAN_ANY,
                    ROLE_QUERY_EXEC_GEN_ASSMNT_PLAN_FAC, ROLE_QUERY_EXEC_GEN_ASSMNT_PLAN_PRG), UserPermAccess.UPDATE,
            List.of(ROLE_UPDATE_STATUS_EXEC_GEN_ASSMNT_PLAN_ANY, ROLE_UPDATE_STATUS_EXEC_GEN_ASSMNT_PLAN_FAC,
                    ROLE_UPDATE_STATUS_EXEC_GEN_ASSMNT_PLAN_PRG));
    Map<UserPermAccess, List<String>> ASSEMTGENPLAN_EXECUTING_ASSEMTGENPLAN = Map.of(UserPermAccess.ADMIN,
            List.of(ROLE_ADMIN_EXEC_GEN_ASSMNT_PLAN_OWN), UserPermAccess.QUERY,
            List.of(ROLE_ADMIN_EXEC_GEN_ASSMNT_PLAN_OWN, ROLE_QUERY_EXEC_GEN_ASSMNT_PLAN_OWN), UserPermAccess.UPDATE,
            List.of());
    Map<UserPermAccess, List<String>> ASSEMTGENPLAN_REVIEW_ASSEMTGENPLANS = Map.of(UserPermAccess.ADMIN,
            List.of(ROLE_ADMIN_REVIEW_GEN_ASSMNT_PLAN_ANY, ROLE_ADMIN_REVIEW_GEN_ASSMNT_PLAN_FAC,
                    ROLE_ADMIN_REVIEW_GEN_ASSMNT_PLAN_PRG), UserPermAccess.QUERY,
            List.of(ROLE_ADMIN_REVIEW_GEN_ASSMNT_PLAN_ANY, ROLE_ADMIN_REVIEW_GEN_ASSMNT_PLAN_FAC,
                    ROLE_ADMIN_REVIEW_GEN_ASSMNT_PLAN_PRG, ROLE_QUERY_REVIEW_GEN_ASSMNT_PLAN_ANY,
                    ROLE_QUERY_REVIEW_GEN_ASSMNT_PLAN_FAC, ROLE_QUERY_REVIEW_GEN_ASSMNT_PLAN_PRG),
            UserPermAccess.UPDATE,
            List.of(ROLE_UPDATE_STATUS_REVIEW_GEN_ASSMNT_PLAN_ANY, ROLE_UPDATE_STATUS_REVIEW_GEN_ASSMNT_PLAN_FAC,
                    ROLE_UPDATE_STATUS_REVIEW_GEN_ASSMNT_PLAN_PRG));
    Map<UserPermAccess, List<String>> ASSEMTGENPLAN_REVIEW_ASSEMTGENPLAN = Map.of(UserPermAccess.ADMIN,
            List.of(ROLE_ADMIN_REVIEW_GEN_ASSMNT_PLAN_OWN), UserPermAccess.QUERY,
            List.of(ROLE_ADMIN_REVIEW_GEN_ASSMNT_PLAN_OWN, ROLE_QUERY_REVIEW_GEN_ASSMNT_PLAN_OWN),
            UserPermAccess.UPDATE, List.of());
    Map<UserPermAccess, List<String>> ASSEMTGENPLAN_CLOSED_ASSEMTGENPLANS = Map.of(UserPermAccess.ADMIN,
            List.of(ROLE_ADMIN_CLOSED_GEN_ASSMNT_PLAN_ANY, ROLE_ADMIN_CLOSED_GEN_ASSMNT_PLAN_FAC,
                    ROLE_ADMIN_CLOSED_GEN_ASSMNT_PLAN_PRG), UserPermAccess.QUERY,
            List.of(ROLE_ADMIN_CLOSED_GEN_ASSMNT_PLAN_ANY, ROLE_ADMIN_CLOSED_GEN_ASSMNT_PLAN_FAC,
                    ROLE_ADMIN_CLOSED_GEN_ASSMNT_PLAN_PRG, ROLE_QUERY_CLOSED_GEN_ASSMNT_PLAN_ANY,
                    ROLE_QUERY_CLOSED_GEN_ASSMNT_PLAN_FAC, ROLE_QUERY_CLOSED_GEN_ASSMNT_PLAN_PRG),
            UserPermAccess.UPDATE,
            List.of(ROLE_UPDATE_STATUS_CLOSED_GEN_ASSMNT_PLAN_ANY, ROLE_UPDATE_STATUS_CLOSED_GEN_ASSMNT_PLAN_FAC,
                    ROLE_UPDATE_STATUS_CLOSED_GEN_ASSMNT_PLAN_PRG));
    Map<UserPermAccess, List<String>> ASSEMTGENPLAN_CLOSED_ASSEMTGENPLAN = Map.of(UserPermAccess.ADMIN,
            List.of(ROLE_ADMIN_CLOSED_GEN_ASSMNT_PLAN_OWN), UserPermAccess.QUERY,
            List.of(ROLE_ADMIN_CLOSED_GEN_ASSMNT_PLAN_OWN, ROLE_QUERY_CLOSED_GEN_ASSMNT_PLAN_OWN),
            UserPermAccess.UPDATE, List.of());
    Map<BasePermLevel, Map<UserPermAccess, List<String>>> ASSEMTGENPLAN_FUTURE_FACULTY_PERMISSIONS = Map.of(
            BasePermLevel.ANY, ASSEMTGENPLAN_FUTURE_FACULTIES, BasePermLevel.OWN,
            ASSEMTGENPLAN_FUTURE_FACULTY);
    Map<BasePermLevel, Map<UserPermAccess, List<String>>> ASSEMTGENPLAN_EXECUTING_FACULTY_PERMISSIONS = Map.of(
            BasePermLevel.ANY, ASSEMTGENPLAN_EXECUTING_FACULTIES,
            BasePermLevel.OWN, ASSEMTGENPLAN_EXECUTING_FACULTY);

    // Mappers aggregated by status for Faculty
    Map<BasePermLevel, Map<UserPermAccess, List<String>>> ASSEMTGENPLAN_REVIEW_FACULTY_PERMISSIONS = Map.of(
            BasePermLevel.ANY, ASSEMTGENPLAN_REVIEW_FACULTIES, BasePermLevel.OWN,
            ASSEMTGENPLAN_REVIEW_FACULTY);
    Map<BasePermLevel, Map<UserPermAccess, List<String>>> ASSEMTGENPLAN_CLOSED_FACULTY_PERMISSIONS = Map.of(
            BasePermLevel.ANY, ASSEMTGENPLAN_CLOSED_FACULTIES, BasePermLevel.OWN,
            ASSEMTGENPLAN_CLOSED_FACULTY);
    Map<BaseStatus, Map<BasePermLevel, Map<UserPermAccess, List<String>>>> ASSEMTGENPLAN_FACULTY_PERMISSIONS = Map.of(
            AssessmentGenPlanStatus.FUTURE, ASSEMTGENPLAN_FUTURE_FACULTY_PERMISSIONS, AssessmentGenPlanStatus.EXECUTING,
            ASSEMTGENPLAN_EXECUTING_FACULTY_PERMISSIONS, AssessmentGenPlanStatus.REVIEW,
            ASSEMTGENPLAN_REVIEW_FACULTY_PERMISSIONS, AssessmentGenPlanStatus.CLOSED,
            ASSEMTGENPLAN_CLOSED_FACULTY_PERMISSIONS);
    // Mappers aggregated by status for ProgAcad
    Map<BasePermLevel, Map<UserPermAccess, List<String>>> ASSEMTGENPLAN_FUTURE_ACADPROG_PERMISSIONS = Map.of(
            BasePermLevel.ANY, ASSEMTGENPLAN_FUTURE_ACADPROGRAMS,
            BasePermLevel.OWN, ASSEMTGENPLAN_FUTURE_ACADPROGRAM);
    Map<BasePermLevel, Map<UserPermAccess, List<String>>> ASSEMTGENPLAN_EXECUTING_ACADPROG_PERMISSIONS = Map.of(
            BasePermLevel.ANY, ASSEMTGENPLAN_EXECUTING_ACADPROGRAMS,
            BasePermLevel.OWN, ASSEMTGENPLAN_EXECUTING_ACADPROGRAM);
    Map<BasePermLevel, Map<UserPermAccess, List<String>>> ASSEMTGENPLAN_REVIEW_ACADPROG_PERMISSIONS = Map.of(
            BasePermLevel.ANY, ASSEMTGENPLAN_REVIEW_ACADPROGRAMS,
            BasePermLevel.OWN, ASSEMTGENPLAN_REVIEW_ACADPROGRAM);
    Map<BasePermLevel, Map<UserPermAccess, List<String>>> ASSEMTGENPLAN_CLOSED_ACADPROG_PERMISSIONS = Map.of(
            BasePermLevel.ANY, ASSEMTGENPLAN_CLOSED_ACADPROGRAMS,
            BasePermLevel.OWN, ASSEMTGENPLAN_CLOSED_ACADPROGRAM);
    Map<BaseStatus, Map<BasePermLevel, Map<UserPermAccess, List<String>>>> ASSEMTGENPLAN_ACADPROG_PERMISSIONS = Map.of(
            AssessmentGenPlanStatus.FUTURE, ASSEMTGENPLAN_FUTURE_ACADPROG_PERMISSIONS,
            AssessmentGenPlanStatus.EXECUTING, ASSEMTGENPLAN_EXECUTING_ACADPROG_PERMISSIONS,
            AssessmentGenPlanStatus.REVIEW, ASSEMTGENPLAN_REVIEW_ACADPROG_PERMISSIONS, AssessmentGenPlanStatus.CLOSED,
            ASSEMTGENPLAN_CLOSED_ACADPROG_PERMISSIONS);
    // Mappers aggregated by status for AssemtGenPlan
    Map<BasePermLevel, Map<UserPermAccess, List<String>>> ASSEMTGENPLAN_FUTURE_ASSEMTGENPLAN_PERMISSIONS = Map.of(
            BasePermLevel.ANY, ASSEMTGENPLAN_FUTURE_ASSEMTGENPLANS, BasePermLevel.OWN,
            ASSEMTGENPLAN_FUTURE_ASSEMTGENPLAN);
    Map<BasePermLevel, Map<UserPermAccess, List<String>>> ASSEMTGENPLAN_EXECUTING_ASSEMTGENPLAN_PERMISSIONS = Map.of(
            BasePermLevel.ANY, ASSEMTGENPLAN_EXECUTING_ASSEMTGENPLANS, BasePermLevel.OWN,
            ASSEMTGENPLAN_EXECUTING_ASSEMTGENPLAN);
    Map<BasePermLevel, Map<UserPermAccess, List<String>>> ASSEMTGENPLAN_REVIEW_ASSEMTGENPLAN_PERMISSIONS = Map.of(
            BasePermLevel.ANY, ASSEMTGENPLAN_REVIEW_ASSEMTGENPLANS, BasePermLevel.OWN,
            ASSEMTGENPLAN_REVIEW_ASSEMTGENPLAN);

    Map<BasePermLevel, Map<UserPermAccess, List<String>>> ASSEMTGENPLAN_CLOSED_ASSEMTGENPLAN_PERMISSIONS = Map.of(
            BasePermLevel.ANY, ASSEMTGENPLAN_CLOSED_ASSEMTGENPLANS, BasePermLevel.OWN,
            ASSEMTGENPLAN_CLOSED_ASSEMTGENPLAN);

    //Mappers for use
    Map<BaseStatus, Map<BasePermLevel, Map<UserPermAccess, List<String>>>> ASSEMTGENPLAN_ASSEMTGENPLAN_PERMISSIONS = Map.of(
            AssessmentGenPlanStatus.FUTURE, ASSEMTGENPLAN_FUTURE_ASSEMTGENPLAN_PERMISSIONS,
            AssessmentGenPlanStatus.EXECUTING, ASSEMTGENPLAN_EXECUTING_ASSEMTGENPLAN_PERMISSIONS,
            AssessmentGenPlanStatus.REVIEW, ASSEMTGENPLAN_REVIEW_ASSEMTGENPLAN_PERMISSIONS,
            AssessmentGenPlanStatus.CLOSED, ASSEMTGENPLAN_CLOSED_ASSEMTGENPLAN_PERMISSIONS);

}
